apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: images
  namespace: image-based-install-operator
spec:
  port:
    targetPort: config-server
  to:
    kind: Service
    name: image-based-install-config
    weight: 100
  wildcardPolicy: None
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: reencrypt
